imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: ssl
    spool:     { type: memory }


fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Szakdolgozat\LayoutBundle\Entity\User

knp_menu:
    twig:
        template: knp_menu.html.twig

    templating: false

    default_renderer: twig

knp_paginator:
    page_range: 2                     # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

easy_admin:
    site_name: 'Adminisztráció'
    entities:
        User:
          label: 'Felhasználók'
          class: Szakdolgozat\LayoutBundle\Entity\User
          list:
            title: '%%entity_label%% listája'
            fields:
              - {property: 'username', label: 'Felhasználónév'}
              - 'email'
              - {property: 'enabled', label: 'Aktivált'}
              - {property: 'lastLogin', label: 'Utoljára belépve'}
          disabled_actions: ['new']
          edit:
            fields:
            - {property: 'username', label: 'Felhasználónév'}
            - 'email'
            - {property: 'enabled', label: 'Aktivált'}
            - {property: 'roles', label: 'Jog'}
            title:  'Felhasználó módosítása'
          show:
            fields:
            - {property: 'username', label: 'Felhasználónév'}
            - 'email'
            - {property: 'lastLogin', label: 'Utoljára belépve'}
            - {property: 'enabled', label: 'Aktivált'}
            - {property: 'roles', label: 'Jog'}
            title:  'Felhasználó adatai'
        Apartment:
          label: 'Apartmanok'
          class: Szakdolgozat\LayoutBundle\Entity\Apartment
          list:
            title: '%%entity_label%% listája'
            fields:
              - {property: 'name', label: 'Neve'}
              - {property: 'city', label: 'Város'}
              - {property: 'highlighted', label: 'Kiemelt'}
          new:
            title: 'Új apartman felvitele'
            fields: ['name', 'city', 'address', 'description', 'webpage', 'climate', 'tv', 'wifi', 'restaurant', 'parking', 'specialparking', 'highlighted']
          show:
            fields: ['name', 'city', 'address', 'description', 'webpage', 'climate', 'tv', 'wifi', 'restaurant', 'parking', 'specialparking', 'highlighted']
          edit:
            fields: ['name', 'city', 'address', 'description', 'webpage', 'climate', 'tv', 'wifi', 'restaurant', 'parking', 'specialparking', 'highlighted']
        Room:
          label: 'Szobák'
          class: Szakdolgozat\LayoutBundle\Entity\Room
          list:
            title: '%%entity_label%% listája'
            fields:
              - {property: 'apartment', label: 'Apartman'}
              - {property: 'roomnumber', label: 'Szobaszám'}
          new:
            fields: ['apartment', 'roomnumber', 'price', 'spot', 'airspace','numberofbed']
          show:
            fields: ['id', 'apartment', 'roomnumber', 'price', 'spot', 'airspace','numberofbed']
          edit:
            fields: ['apartment', 'roomnumber', 'price', 'spot', 'airspace','numberofbed']
        Reservation:
          label: 'Foglalások'
          class: Szakdolgozat\LayoutBundle\Entity\Reservation
          disabled_actions: ['new']
          list:
            title: '%%entity_label%% listája'
            fields: ['room.apartment', 'room', 'user', 'arrivaldate', 'numberofdays', 'status']
          show:
            fields: ['room.apartment', 'room', 'user', 'arrivaldate', 'numberofdays', 'specialrequest', 'status']
          edit:
            fields: ['room', 'user', 'arrivaldate', 'numberofdays', 'specialrequest', 'status']
        City:
          label: 'Városok'
          class: Szakdolgozat\LayoutBundle\Entity\City
          list:
            title: '%%entity_label%%'
            fields:
              - {property: 'city', label: 'Város'}
          show:
            fields:
              - {property: 'city', label: 'Város'}
          edit:
            fields:
              - {property: 'city', label: 'Város'}
          new:
            fields:
              - {property: 'city', label: 'Város'}

    design:
            brand_color: '#cc0033'
            form_theme: 'horizontal'

    formats:
            date:     'Y.m.d.'
            time:     'H:i'
            datetime: 'Y.m.d. H:i:s'