fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

homepage:
    path:     /
    defaults: { _controller: SzakdolgozatLayoutBundle:Home:index }
    requirements:
     methods: GET|POST

szallasok:
    path:     /szallasok
    defaults: { _controller: SzakdolgozatLayoutBundle:Apartments:index }
    requirements:
     methods: GET|POST

kapcsolat:
    path:     /kapcsolat
    defaults: { _controller: SzakdolgozatLayoutBundle:Home:index }
    requirements:
     methods: GET|POST

szallas:
    path:     /szallas/{id}
    defaults: { _controller: SzakdolgozatLayoutBundle:Apartment:index, id: 0 }
    requirements:
     methods: GET
